---
apiVersion: v1
kind: Pod
metadata:
  name: gol
  labels:
    app: tomcat
spec:
  containers:
    - name: gol
      image: hema789/hello:gol-3.0
      ports:
        - containerPort: 8080
        
