---
apiVersion: v1
kind: Pod
metadata:
  name: alphine
spec:
  containers:
  - name: alphine
    image: alphine
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine
      args:
        - sleep
        - 10s
---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins/jenkins:jdk11
      ports:
        containerPort: 8080
    - name: httpd
      image: httpd
      ports:
        containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: alpinehema
spec: 
  containers:
    - name: alpine1
      image: aplpine3
      args:
        - sleep
        - 1d
    - name: alpine2
      image: alpine:3
      args:
        - sleep
        - 10s
        
