---
apiVersion: v1
kind: Pod
metadata:
  name: alphine
spec:
  containers:
  - name: alphine
    image: alphine
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine
      args:
        - sleep
        - 10s
---
