---
apiVersion: v1
kind: Service
metadata:
  name: sql-nop-svc
  labels:
    app: mysql
spec:
  ports:
    - port: 5000
      name: nopCommerce
      protocol: TCP
    - port: 3306
      name: mysql
      protocol: TCP
  selector: 
    app: mysql
  type: LoadBalancer

    
    