---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: 'nopcommerce'
  labels:
    name: web
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata: 
      name: 'noppod'
      labels:
        app: web
    spec:
      containers:
        - name: nopcommerce
          image: hema789/hello:nop-2.0
          ports:
            - containerPort: 5000
              protocol: TCP


FROM alpine
LABEL author='hema'
CMD ["sleep","1d"]



