---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: replicanop
  labels:
    name: web
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata: 
      name: noppod
      labels:
        app: web
    spec:
      containers:
        - name: nopCommerce
          image:
          ports:
            - containerPort: 5000
              protocol: TCP
              




