---
apiVersion: v1
kind: ReplicaSet
metadata: 
  app: httpd
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      web: nginx
      labels:
        app: httpd
    spec:
      activeDeadlineSeconds: 3
      affinity: 2
      containers:
        - name: httpd
          image: httpd
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 3
            successThreshold: 3
            httpGet: 
              path: /
              port: 80
          resources:
            requests: 
              memory: "64Mi"
              cpu: "256m"