# always restart the container 
---
apiVersion: v1
kind: Pod
metadata:
  name: restartpolicy1
spec:
  restartPolicy: Always
  containers:
    - name: alpine
      image: alpine:3
      args:
        - sleep
        - 10s

---
#never restart
---
apiVersion: v1
kind: Pod
metadata:
  name: restartpolicy2
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine:3
      args:
        - sleep
        - 10s






# onfailure
---
apiVersion: v1
kind: Pod
metadata:
  name: restartpolicy3
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine:3
      args:
        - sleep
        - 10SM
---
apiVersion: v1
kind: Pod
metadata:
  name: restartpolicy3
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpine
      image: alpine:3
      args:
        - sleep
        - 10s
