---
apiVersion: v1
kind: Secret
metadata:
  name: secret-cm
data:
  region: dXMtZWFzdC0xCg==
  username: QVdTCg==
  password-stdin: NTY4MjI5NDg4MTkwLmRrci5lY3IudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20K





---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-secret
spec:
  containers: 
    - name: alpine
      image: 568229488190.dkr.ecr.us-east-1.amazonaws.com/hemachaitanya:latest
      args:
        - sleep
        - 1d
  imagePullSecrets:
    name: secret-cm
    
      

