---
apiVersion: v1
kind: Pod
metadata:
  name: spc-nop
spec:
  containers:
    - name: springpetclinic
      image: hema789/hello:spc-1.0
      ports:
        - containerPort: 8080
          protocol: "TCP"
    - name: nopcommerce
      image: hema789/hello:nop-2.0
      ports:
        - containerPort: 5000



---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: petclinic
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: spc-nop
spec:
  containers:
    - name: springpetclinic
      image: hema789/hello:spc-1.0
      ports:
        - containerPort: 8080
          protocol: "TCP"
