---
apiVersion: v1
kind: Pod
metadata:
  name: my-pvc
spec:
  containers:
    env:
      - name: MYSQL_ROOT_PASSWORD      #### env variable name ####
        value: rootroot           ##env variable value #####
      - name: MYSQL_DATABASE
        value: mysqldb
      - name: MYSQL_USER
        value: hema
      - name: MYSQL_PASSWORD
        value: rootroot
    





[Refer Here]
         
          