---
apiVersion: v1
kind: Pod
metadata:
  app: apache2
spec:
  activeDeadlineSeconds: 2
  tolerations: 
    - key: poc
      operator: Equal
      value: "true"
  containers:
    - name: apache2
      image: httpd
      ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Pod
metadata:
  app: nginx
spec:
  activeDeadlineSeconds: 2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: type
              operator: In
              values:
                - app-01
      preferredDuringSchedulingIgnoredDuringExecution:
        weight: 1
        preference: 
          matchExpressions:
            - key: name
              operator: In
              values: 
                - app-02

    


