---
apiVersion: v1
kind: Pod
metadata:
  name: taint
spec:
  activeDeadlineSeconds: 2
  tolerations: 
    - key: poc
      operator: Equal
      value: "true"
  containers:
    - name: apache2
      image: httpd
      ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Pod
metadata:
  name: affinity
spec:
  activeDeadlineSeconds: 2
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: disktype
              operator: In
              values:
                - ssd
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference: 
            matchExpressions:
              - key: name
                operator: In
                values: 
                  - app-02

    


