---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: hema
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: nginx
    strategy:
      rollingUpdate:
        maxSurge: 30%
        maxUnavailable: 40%
    template:
      metadata:
        labels: 
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx
            ports:
              - name: nginx
                containerPort: 80
                protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    label: nginx-svc
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: loadbalancer


  