---
apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-controller
  labels:
    app: urwish
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      name: urwish
      labels:
        app: urwish
    spec:
      containers:
        - name: urwish
          image: httpd
          ports:
            - name: port
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 2
            successThreshold: 2
            terminationGracePeriodSeconds: 2
            timeoutSeconds: 2


      
              